15 allow compiler to use asconfig
massalabs/massa-sc-compiler pull request #16
Opened 2023-06-08 13:47 UTC by julienbrs

close #15

2023-06-09 12:50 UTC, 0xSwapFeeder commented
No sure to understand these changes, isn't asc using asconfig.json by default ?

2023-06-09 13:15 UTC, julienbrs commented
> No sure to understand these changes, isn't asc using asconfig.json by default ?

Indeed asc use asconfig.json by default. However, in that file, we're using the AssemblyScript compiler programmatically with the asc.main method. I might be wrong, but it doesn't automatically load the asconfig.json. Thus, we need to manually populate arguments for the function

2023-06-12 09:53 UTC, gregLibert requested changes

2023-06-12 09:53 UTC, gregLibert commented on src/compiler.ts
> +    if ((options as any).transformer) {
Can you use a type instead of any ?

2023-06-12 09:53 UTC, gregLibert commented on src/compiler.ts
> +      argv.push((options as any).transformer[0]);
same here

2023-06-12 09:53 UTC, gregLibert commented on src/compiler.ts
> +      argv.push((options as any).transformer[0]);
What happens if you have more than one trasnformer ?

2023-06-12 13:07 UTC, gregLibert requested changes

2023-06-12 13:07 UTC, gregLibert commented on src/compiler.ts
> +type CompilationOptions = APIOptions & {
Why aren't you using compiler [Option](https://github.com/AssemblyScript/assemblyscript/blob/main/src/compiler.ts#L231)?

2023-06-12 15:24 UTC, gregLibert approved these changes

2023-06-12 15:24 UTC, merged